version: '3'
services:
  database:
    image: "postgres:12.4"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postdb
    volumes:
      - ./database-data:/var/lib/postgresql/data/